apiVersion: v1
name: nodeport-proxy
version: 1.5.4
appVersion: v2.14.0
description: Kubermatic nodeport-proxy
keywords:
- kubermatic
- nodeport-proxy
home: https://www.kubermatic.io/
sources:
- https://github.com/kubermatic/nodeport-proxy
maintainers:
- name: Loodse GmbH
  email: support@loodse.com
