apiVersion: v1
name: kubermatic
version: 1.0.22
appVersion: 'v2.12.5'
description: Kubermatic chart for master and/or seed clusters.
keywords:
- kubermatic
home: https://www.kubermatic.io/
sources:
- https://github.com/kubermatic/kubermatic
maintainers:
- name: Loodse GmbH
  email: support@loodse.com
