apiVersion: v1
name: kubermatic
version: 1.1.2
appVersion: 'latest'
description: Kubermatic chart for master and/or seed clusters.
keywords:
- kubermatic
home: https://www.kubermatic.io/
sources:
- https://github.com/kubermatic/kubermatic
maintainers:
- name: Loodse GmbH
  email: support@loodse.com
